import React from 'react';

import { DeleteConfirmModal } from './components/DeleteConfirmModal/DeleteConfirmModal';
import RestoreConfirmModal from './components/RestoreConfirmModal/RestoreConfirmModal';
import Input from './components/Input/Input';
import MultiInput from './components/MultiInput/MultiInput';
import Label from './components/Label/Label';
import Notice from './components/Notice/Notice';
import Button from './components/Button/Button';
import ColorPicker from './components/ColorPicker/ColorPicker';
import FileUploader from './components/FileUploader/FileUploader';
import Tab from './components/Tab/Tab';
import Chip from './components/Chip/Chip';
import MultiSelect from './components/MultiSelect/MultiSelect';
import TextArea from './components/TextArea/TextArea';
import MultiTab from './components/MultiTab/MultiTab';
import Rating from './components/Rating/Rating';
import Calendar from './components/Calendar/Calendar';
import Template from './components/Template/Template';
import { DateSelect } from './components/DateSelect/DateSelect';
import { IsDeleteSelect } from './components/IsDeleteSelect/IsDeleteSelect';
import { ListPagination } from './components/ListPagination/ListPagination';
import { ListTable } from './components/ListTable/ListTable';
import { PageSizeSelect } from './components/PageSizeSelect/PageSizeSelect';
import { ModalContainer } from './components/ModalContainer/ModalContainer';
import Box from './components/Box/Box';
import Accordion from './components/Accordion/Accordion';
import Select from './components/Select/Select';
import Text from './components/Text/Text';
import Toggle from './components/Toggle/Toggle';
import Item from './components/Item/Item';
import Pagination from './components/Pagination/Pagination';
import Dropdown from './components/Dropdown/Dropdown';

type DesktopProps = {
    children: React.ReactNode;
};

export const Desktop = ({ children }: DesktopProps) => <>{children}</>;

Desktop.DeleteConfirmModal = DeleteConfirmModal;
Desktop.RestoreConfirmModal = RestoreConfirmModal;
Desktop.DateSelect = DateSelect;
Desktop.IsDeleteSelect = IsDeleteSelect;
Desktop.ListPagination = ListPagination;
Desktop.ListTable = ListTable;
Desktop.PageSizeSelect = PageSizeSelect;
Desktop.ModalContainer = ModalContainer;
Desktop.Input = Input;
Desktop.MultiInput = MultiInput;
Desktop.Label = Label;
Desktop.Notice = Notice;
Desktop.Button = Button;
Desktop.ColorPicker = ColorPicker;
Desktop.FileUploader = FileUploader;
Desktop.Tab = Tab;
Desktop.Chip = Chip;
Desktop.MultiSelect = MultiSelect;
Desktop.TextArea = TextArea;
Desktop.MultiTab = MultiTab;
Desktop.Rating = Rating;
Desktop.Calendar = Calendar;
Desktop.Template = Template;
Desktop.Box = Box;
Desktop.Accordion = Accordion;
Desktop.Select = Select;
Desktop.Text = Text;
Desktop.Toggle = Toggle;
Desktop.Item = Item;
Desktop.Pagination = Pagination;
Desktop.Dropdown = Dropdown;
